name: laravel-vue-inertia-boilerplate
type: laravel
docroot: public
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
nodejs_version: "18"
web_environment:
  - VITE_SERVER_HOST=0.0.0.0
hooks:
  post-start:
    - exec: npm run dev
  pre-stop:
    - exec: npm run build
web_extra_exposed_ports:
  - name: node-vite
    container_port: 5173
    http_port: 5172
    https_port: 5173